### ISSUE TITLE
ImportError: No module named errors

### ISSUE THREAD

**Issue by StL-Jim** [Celeo/Preston#11]
:from prest import Prest
:
:prest = Prest()
:--
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-9f8cdcfba53a> in <module>()
----> 1 from prest import Prest
      2 
      3 prest = Prest()

/usr/local/lib/python2.7/dist-packages/prest/__init__.py in <module>()
----> 1 from prest.prest import *
      2 from prest.prest import __version__
      3 from prest.errors import *
      4 
      5 

/usr/local/lib/python2.7/dist-packages/prest/prest.py in <module>()
      7 import requests
      8 
----> 9 from prest.errors import *
     10 from prest.cache import *
     11 

ImportError: No module named errors

**Comment by Celeo** [comment]
Good morning. Unfortunately, at this time, Preston only supports Python 3.

This isn't made very clear, so I'll update the README to specifically state that.

**Comment by StL-Jim** [comment]
Thank you for the response.  I haven’t gotten around to be ‘good’ at python 3 yet.  I’m old and stuck in my python 2.7 ways.
