### ISSUE TITLE
Error when using post_op() to set waypoint

### ISSUE THREAD

**Issue by themrrigs** [Celeo/Preston#26]
I get `<Response [400]>` with the error `{'error': "'add_to_beginning' is required, 'clear_other_waypoints' is required, 'destination_id' is required"}` when I try to make a post request setting the waypoint. Here is my code for the post request:
```
test = {
    "add_to_beginning": "false",
    "clear_other_waypoints": "false",
    "destination_id": "30000142"
}
print(preston.post_op("post_ui_autopilot_waypoint", post_data=test, path_data=None))
```

**Comment by Celeo** [comment]
Hi,

I've pushed a fix in [4.4.0](https://pypi.org/project/preston/4.4.0/). Can you see if that resolves this?
