### ISSUE TITLE
The library refreshes the access token and stores it but does not update its own session headers. (401 error)

### ISSUE THREAD

**Issue by Visoral** [Celeo/Preston#33]
In `__init__`, `_update_access_token_header` will be called after `_try_refresh_access_token` but not in `whoami`, `get_path`, `post_path`?
This causes a 401 error because the library has an updated token in `self.access_token` but it didn't update `self.session.headers`.
I'm really bad at programming, so I could be totally wrong about it.

**Comment by Celeo** [comment]
Ah, yup - interesting. I'll push an update and see if this is resolved.

**Comment by Celeo** [comment]
Version `4.7.0` published. Let me know if that helps!

**Comment by Visoral** [comment]
It's working fine now. Thank you!

**Comment by Celeo** [comment]
Super, thanks for reaching out!
